package com.yassinekamouss.smartbudget.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF006C4C)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF89F8C6)
val OnPrimaryContainerLight = Color(0xFF002114)
val SecondaryLight = Color(0xFF4C6357)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCEE9DB)
val OnSecondaryContainerLight = Color(0xFF092016)
val TertiaryLight = Color(0xFF3D6373)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC1E8FB)
val OnTertiaryContainerLight = Color(0xFF001F29)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFBFDF9)
val OnBackgroundLight = Color(0xFF191C1A)
val SurfaceLight = Color(0xFFFBFDF9)
val OnSurfaceLight = Color(0xFF191C1A)

val PrimaryDark = Color(0xFF6CDBAB)
val OnPrimaryDark = Color(0xFF003825)
val PrimaryContainerDark = Color(0xFF005138)
val OnPrimaryContainerDark = Color(0xFF89F8C6)
val SecondaryDark = Color(0xFFB3CCBF)
val OnSecondaryDark = Color(0xFF1F352A)
val SecondaryContainerDark = Color(0xFF354B40)
val OnSecondaryContainerDark = Color(0xFFCEE9DB)
val TertiaryDark = Color(0xFFA5CCDF)
val OnTertiaryDark = Color(0xFF073543)
val TertiaryContainerDark = Color(0xFF244C5A)
val OnTertiaryContainerDark = Color(0xFFC1E8FB)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF191C1A)
val OnBackgroundDark = Color(0xFFE1E3DF)
val SurfaceDark = Color(0xFF191C1A)
val OnSurfaceDark = Color(0xFFE1E3DF)

// Category Colors
val CategoryFood = Color(0xFFE57373)
val CategoryTransport = Color(0xFF64B5F6)
val CategoryHousing = Color(0xFF81C784)
val CategoryHealth = Color(0xFF4DB6AC)
val CategoryLeisure = Color(0xFFFFB74D)
val CategoryEducation = Color(0xFFBA68C8)
val CategoryOther = Color(0xFF90A4AE)
